### ISSUE TITLE
Please Setup Service Context before making get CompanyInfo call

### ISSUE THREAD

**Issue by asadmughal92** [spinen/laravel-quickbooks-client#59] opened 2022-12-05 12:21 UTC
i have followed the documentation still get this error and I don't have a frontend I want to create APIs for sending data in quikcbooks

QuickBooksOnline\API\Exception\SdkException with message 
Please Setup Service Context before making get CompanyInfo call

**Comment by jimmypuckett** [comment] 2022-12-05 13:43
There is no need to duplicate your problem on multiple issues.  You need to provide more information about your request.  Like what version of Laravel you are using, which version of the package you are using, etc.

Also, did you review the previous issues to see if you are having a similar issue?  From a quick search, I think that this is a duplicate of #8

If this is not a duplicate of #8, then please provide more details & reopen.

Thanks.

**Closed as completed by jimmypuckett** 2022-12-05 13:43 UTC

**Comment by asadmughal92** [comment] 2022-12-05 14:17
Laravel version 9.0 and basically i am having issues while connecting i
have followed the guide properly

**Comment by jimmypuckett** [comment] 2022-12-05 14:22
Please post the output of your tinker from doing the commands posted here...

https://github.com/spinen/laravel-quickbooks-client/issues/8#issuecomment-608709072

Make sure to redact the sensitive parts.
