### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by hemant444u** [spinen/laravel-quickbooks-client#23] opened 2020-04-17 07:34 UTC
Please let me know, how can i use this package ?

**Comment by jimmypuckett** [comment] 2020-04-17 10:43
I’m sorry, but I do t know where to begin to teach you how to use a composer package to n Laravel. There are some awesome resources out there like Laracasts to learn about programming. I would start there. Then I would review the readme with this package for specifics about this package. 

Hope you have fun on your journey!

Duplicate of #22

**Closed as completed by jimmypuckett** 2020-04-17 10:43 UTC
